name: Replace old strings with new strings

on:
  push:
    branches:
      - test

jobs:
  replace-word:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Replace multiple strings in text files
      run: |
        filePaths=("sample.txt" "sample1.txt" "sample2.txt")
        oldStrings=("dev" "test" "example")
        newStrings=("sit" "prod" "sample")

        for filePath in "${filePaths[@]}"; do
          if [ -f "$filePath" ]; then
            for i in "${!oldStrings[@]}"; do
              sed -i "s/${oldStrings[i]}/${newStrings[i]}/g" "$filePath"
              echo "Replaced '${oldStrings[i]}' with '${newStrings[i]}' in $filePath"
            done
            echo "Updated $filePath:"
            cat "$filePath"
          else
            echo "$filePath does not exist."
          fi
        done
