name: Replace old strings with new strings

on:
  push:
    branches:
      - test1

jobs:
  replace-word:
    runs-on: windows-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Replace multiple strings in text files
      run: |
        $filePaths = @('sample.txt', 'sample1.txt', 'sample2.txt')
        $oldStrings = @('dev', 'test', 'example')
        $newStrings = @('sit', 'prod', 'sample')

        foreach ($filePath in $filePaths) {
          if (Test-Path $filePath) {
            for ($i = 0; $i -lt $oldStrings.Count; $i++) {
              (Get-Content $filePath) -replace [regex]::Escape($oldStrings[$i]), $newStrings[$i] | Set-Content $filePath
              Write-Host "Replaced '$($oldStrings[$i])' with '$($newStrings[$i])' in $filePath"
            }
            Write-Host "Updated $filePath:"
            Get-Content $filePath
          } else {
            Write-Host "$filePath does not exist."
          }
        }
